name: deploy docker container

on:
  workflow_dispatch:
    inputs:
        tag:
          description: 'Tag of the docker image'
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.1.0
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                docker pull edikgoose/dengovie:${{ github.event.inputs.tag }} 
                docker remove --force dengovie
                docker run \
                    -e TOKEN='${{ secrets.TELEGRAM_TOKEN}}' \
                    -e PG_HOST='${{ env.PG_HOST }}' \
                    -e PG_PORT='${{ env.PG_PORT }}' \
                    -e PG_USER='${{ env.PG_USER }}' \
                    -e PG_DATABASE='${{ env.PG_DATABASE}}' \
                    -e PG_PASSWORD='${{ secrets.PG_PASSWORD }}' \
                    -e PG_SSL='require' \
                    -d \
                    --name dengovie \
                    edikgoose/dengovie:${{ github.event.inputs.tag }}
